sudo: false
dist: trusty
git:
  depth: 2
language: node_js
node_js:
- &release_node 4.4
- 6
- 7
- 8
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_AUTH_TOKEN}
  on:
    tags: true
    repo: bespokejs/generator-bespoke
    node: *release_node
